// Mock data for CADIVI Capacity Dashboard

export const dashboardOverviewData = {
  // KPI Row 1 - Data coverage
  totalMaterials: 5291,
  materialsWithData: 4334,
  materialsMissing: 957,
  pendingApproval: 12,

  // KPI Row 2 - Machines by process
  machinesByProcess: [
    { process: "Kéo", count: 25, plants: 3 },
    { process: "Xoắn", count: 58, plants: 3 },
    { process: "Giáp", count: 9, plants: 3 },
    { process: "Bọc", count: 24, plants: 3 },
  ],

  // Coverage by process (for chart)
  coverageByProcess: [
    { process: "Kéo", hasData: 88, missing: 12 },
    { process: "Xoắn", hasData: 76, missing: 24 },
    { process: "Giáp", hasData: 92, missing: 8 },
    { process: "Bọc", hasData: 81, missing: 19 },
  ],

  // Speed comparison (design vs actual)
  speedComparison: [
    { process: "Kéo", design: 756, actual: 588 },
    { process: "Xoắn", design: 248, actual: 166 },
    { process: "Giáp", design: 7.2, actual: 7.2 },
    { process: "Bọc", design: 178, actual: 162 },
  ],

  // Scatter plot data - Top 20 materials (Xoắn)
  scatterData: [
    { plant: "Cadivi Đà Nẵng", design: 220, actual: 165, material: "53000123" },
    { plant: "Cadivi Đà Nẵng", design: 245, actual: 178, material: "53000145" },
    { plant: "Cadivi Đà Nẵng", design: 260, actual: 192, material: "53000167" },
    { plant: "Cadivi Long Thành", design: 230, actual: 155, material: "53000089" },
    { plant: "Cadivi Long Thành", design: 250, actual: 170, material: "53000234" },
    { plant: "Cadivi Long Thành", design: 255, actual: 168, material: "53000456" },
    { plant: "Cadivi Tân Á", design: 210, actual: 148, material: "53000345" },
    { plant: "Cadivi Tân Á", design: 240, actual: 160, material: "53000567" },
    { plant: "Cadivi Tân Á", design: 265, actual: 175, material: "53000789" },
    { plant: "Cadivi Bắc Ninh", design: 235, actual: 162, material: "53000890" },
    { plant: "Cadivi Bắc Ninh", design: 258, actual: 180, material: "53000901" },
    { plant: "Cadivi Đà Nẵng", design: 248, actual: 185, material: "53000234" },
    { plant: "Cadivi Long Thành", design: 242, actual: 172, material: "53000567" },
    { plant: "Cadivi Tân Á", design: 252, actual: 166, material: "53000678" },
    { plant: "Cadivi Bắc Ninh", design: 238, actual: 158, material: "53000789" },
    { plant: "Cadivi Đà Nẵng", design: 262, actual: 190, material: "53000345" },
    { plant: "Cadivi Long Thành", design: 228, actual: 152, material: "53000456" },
    { plant: "Cadivi Tân Á", design: 246, actual: 164, material: "53000890" },
    { plant: "Cadivi Bắc Ninh", design: 254, actual: 176, material: "53000123" },
    { plant: "Cadivi Đà Nẵng", design: 232, actual: 168, material: "53000901" },
  ],

  // Pareto chart - Missing data by process
  paretoData: [
    { process: "Xoắn", count: 420, cumulative: 43 },
    { process: "Bọc", count: 310, cumulative: 75 },
    { process: "Kéo", count: 145, cumulative: 90 },
    { process: "Giáp", count: 82, cumulative: 100 },
  ],

  // Plant summaries
  plantSummaries: [
    {
      plant: "Cadivi Đà Nẵng",
      materialCount: 1820,
      coverage: 84,
      machines: 32,
      processes: 4,
    },
    {
      plant: "Cadivi Long Thành",
      materialCount: 1640,
      coverage: 79,
      machines: 28,
      processes: 4,
    },
    {
      plant: "Cadivi Tân Á",
      materialCount: 1831,
      coverage: 72,
      machines: 30,
      processes: 4,
    },
    {
      plant: "Cadivi Bắc Ninh",
      materialCount: 1000,
      coverage: 88,
      machines: 26,
      processes: 4,
    },
  ],

  // Top 20 materials table
  topMaterials: [
    {
      code: "53000234",
      description: "Cáp điện 3x6 Cu/XLPE/PVC 0.6/1kV",
      process: "Xoắn",
      plant: "Cadivi Đà Nẵng",
      machine: "TW-DN-05",
      designSpeed: 245,
      actualSpeed: 178,
      outputKm: 12.8,
      status: "complete",
    },
    {
      code: "53000456",
      description: "Cáp điện 4x10 Cu/XLPE/PVC 0.6/1kV",
      process: "Xoắn",
      plant: "Cadivi Long Thành",
      machine: "TW-LT-12",
      designSpeed: 255,
      actualSpeed: 168,
      outputKm: 11.5,
      status: "complete",
    },
    {
      code: "56001234",
      description: "Cáp điện 2x4 Cu/PVC/SWA/PVC",
      process: "Bọc",
      plant: "Cadivi Tân Á",
      machine: "SH-TA-08",
      designSpeed: 180,
      actualSpeed: 165,
      outputKm: 13.2,
      status: "complete",
    },
    {
      code: "52000567",
      description: "Dây đồng cứng BC 2.5mm²",
      process: "Kéo",
      plant: "Cadivi Bắc Ninh",
      machine: "DR-BN-03",
      designSpeed: 780,
      actualSpeed: 620,
      outputKm: 28.5,
      status: "complete",
    },
    {
      code: "53000789",
      description: "Cáp điện 3x16 Cu/XLPE/PVC 0.6/1kV",
      process: "Xoắn",
      plant: "Cadivi Đà Nẵng",
      machine: "TW-DN-08",
      designSpeed: 240,
      actualSpeed: 160,
      outputKm: 9.8,
      status: "missing",
    },
    {
      code: "55000345",
      description: "Cáp điện 4x25 Cu/XLPE/DSTA/PVC",
      process: "Giáp",
      plant: "Cadivi Long Thành",
      machine: "AR-LT-02",
      designSpeed: 7.2,
      actualSpeed: 7.2,
      outputKm: 1.8,
      status: "complete",
    },
    {
      code: "56001567",
      description: "Cáp điện 3x6 Cu/PVC/SWA/PVC",
      process: "Bọc",
      plant: "Cadivi Tân Á",
      machine: "SH-TA-05",
      designSpeed: 175,
      actualSpeed: 158,
      outputKm: 12.1,
      status: "complete",
    },
    {
      code: "52000890",
      description: "Dây đồng mềm BC 4.0mm²",
      process: "Kéo",
      plant: "Cadivi Bắc Ninh",
      machine: "DR-BN-05",
      designSpeed: 760,
      actualSpeed: 595,
      outputKm: 26.8,
      status: "missing",
    },
    {
      code: "53001234",
      description: "Cáp điện 4x6 Cu/XLPE/PVC 0.6/1kV",
      process: "Xoắn",
      plant: "Cadivi Đà Nẵng",
      machine: "TW-DN-10",
      designSpeed: 250,
      actualSpeed: 170,
      outputKm: 11.2,
      status: "complete",
    },
    {
      code: "56001890",
      description: "Cáp điện 4x16 Cu/PVC/SWA/PVC",
      process: "Bọc",
      plant: "Cadivi Long Thành",
      machine: "SH-LT-06",
      designSpeed: 168,
      actualSpeed: 155,
      outputKm: 10.8,
      status: "complete",
    },
    {
      code: "52001123",
      description: "Dây đồng cứng BC 6.0mm²",
      process: "Kéo",
      plant: "Cadivi Tân Á",
      machine: "DR-TA-02",
      designSpeed: 740,
      actualSpeed: 580,
      outputKm: 25.2,
      status: "complete",
    },
    {
      code: "53002345",
      description: "Cáp điện 3x25 Cu/XLPE/PVC 0.6/1kV",
      process: "Xoắn",
      plant: "Cadivi Bắc Ninh",
      machine: "TW-BN-04",
      designSpeed: 235,
      actualSpeed: 162,
      outputKm: 8.5,
      status: "missing",
    },
    {
      code: "55000678",
      description: "Cáp điện 4x35 Cu/XLPE/DSTA/PVC",
      process: "Giáp",
      plant: "Cadivi Đà Nẵng",
      machine: "AR-DN-01",
      designSpeed: 7.0,
      actualSpeed: 7.0,
      outputKm: 1.6,
      status: "complete",
    },
    {
      code: "56002123",
      description: "Cáp điện 3x10 Cu/PVC/SWA/PVC",
      process: "Bọc",
      plant: "Cadivi Long Thành",
      machine: "SH-LT-09",
      designSpeed: 172,
      actualSpeed: 162,
      outputKm: 11.8,
      status: "complete",
    },
    {
      code: "52001456",
      description: "Dây đồng mềm BC 10mm²",
      process: "Kéo",
      plant: "Cadivi Tân Á",
      machine: "DR-TA-06",
      designSpeed: 720,
      actualSpeed: 565,
      outputKm: 22.4,
      status: "complete",
    },
    {
      code: "53002678",
      description: "Cáp điện 4x16 Cu/XLPE/PVC 0.6/1kV",
      process: "Xoắn",
      plant: "Cadivi Bắc Ninh",
      machine: "TW-BN-07",
      designSpeed: 242,
      actualSpeed: 172,
      outputKm: 10.2,
      status: "complete",
    },
    {
      code: "55000901",
      description: "Cáp điện 3x50 Cu/XLPE/DSTA/PVC",
      process: "Giáp",
      plant: "Cadivi Đà Nẵng",
      machine: "AR-DN-03",
      designSpeed: 6.8,
      actualSpeed: 6.8,
      outputKm: 1.4,
      status: "missing",
    },
    {
      code: "56002456",
      description: "Cáp điện 4x25 Cu/PVC/SWA/PVC",
      process: "Bọc",
      plant: "Cadivi Long Thành",
      machine: "SH-LT-11",
      designSpeed: 165,
      actualSpeed: 152,
      outputKm: 9.6,
      status: "complete",
    },
    {
      code: "52001789",
      description: "Dây đồng cứng BC 16mm²",
      process: "Kéo",
      plant: "Cadivi Tân Á",
      machine: "DR-TA-08",
      designSpeed: 700,
      actualSpeed: 548,
      outputKm: 20.8,
      status: "complete",
    },
    {
      code: "53003012",
      description: "Cáp điện 3x35 Cu/XLPE/PVC 0.6/1kV",
      process: "Xoắn",
      plant: "Cadivi Bắc Ninh",
      machine: "TW-BN-09",
      designSpeed: 238,
      actualSpeed: 158,
      outputKm: 7.8,
      status: "complete",
    },
  ],
};

// Plant detail data (for Đà Nẵng example)
export const plantDetailData = {
  "Cadivi Đà Nẵng": {
    totalMaterials: 1820,
    coverage: 84,
    missingData: 291,
    totalMachines: 32,
    processes: 4,

    // Coverage by process for this plant
    coverageByProcess: [
      { process: "Kéo", coverage: 88 },
      { process: "Xoắn", coverage: 85 },
      { process: "Giáp", coverage: 92 },
      { process: "Bọc", coverage: 78 },
    ],

    // Top 10 machines by actual speed
    topMachines: [
      { machine: "DR-DN-01", actualSpeed: 645, process: "Kéo" },
      { machine: "DR-DN-03", actualSpeed: 628, process: "Kéo" },
      { machine: "DR-DN-05", actualSpeed: 610, process: "Kéo" },
      { machine: "TW-DN-05", actualSpeed: 185, process: "Xoắn" },
      { machine: "TW-DN-08", actualSpeed: 178, process: "Xoắn" },
      { machine: "TW-DN-10", actualSpeed: 170, process: "Xoắn" },
      { machine: "SH-DN-02", actualSpeed: 168, process: "Bọc" },
      { machine: "SH-DN-05", actualSpeed: 162, process: "Bọc" },
      { machine: "AR-DN-01", actualSpeed: 7.2, process: "Giáp" },
      { machine: "AR-DN-03", actualSpeed: 6.8, process: "Giáp" },
    ],

    // Machines by process
    machinesByProcess: {
      Kéo: [
        {
          machine: "DR-DN-01",
          designSpeed: 780,
          actualSpeed: 645,
          efficiency: 83,
          outputKm: 29.2,
          outputKg: 1850,
          materialCount: 145,
          status: "complete",
        },
        {
          machine: "DR-DN-03",
          designSpeed: 780,
          actualSpeed: 628,
          efficiency: 81,
          outputKm: 28.5,
          outputKg: 1820,
          materialCount: 138,
          status: "complete",
        },
        {
          machine: "DR-DN-05",
          designSpeed: 780,
          actualSpeed: 610,
          efficiency: 78,
          outputKm: 27.8,
          outputKg: 1780,
          materialCount: 142,
          status: "missing",
        },
        {
          machine: "DR-DN-07",
          designSpeed: 760,
          actualSpeed: 595,
          efficiency: 78,
          outputKm: 26.8,
          outputKg: 1720,
          materialCount: 128,
          status: "complete",
        },
        {
          machine: "DR-DN-09",
          designSpeed: 760,
          actualSpeed: 580,
          efficiency: 76,
          outputKm: 26.2,
          outputKg: 1680,
          materialCount: 135,
          status: "complete",
        },
      ],
      Xoắn: [
        {
          machine: "TW-DN-05",
          designSpeed: 248,
          actualSpeed: 185,
          efficiency: 75,
          outputKm: 13.2,
          outputKg: 890,
          materialCount: 68,
          status: "complete",
        },
        {
          machine: "TW-DN-08",
          designSpeed: 245,
          actualSpeed: 178,
          efficiency: 73,
          outputKm: 12.8,
          outputKg: 865,
          materialCount: 72,
          status: "complete",
        },
        {
          machine: "TW-DN-10",
          designSpeed: 250,
          actualSpeed: 170,
          efficiency: 68,
          outputKm: 11.8,
          outputKg: 820,
          materialCount: 65,
          status: "missing",
        },
        {
          machine: "TW-DN-12",
          designSpeed: 242,
          actualSpeed: 168,
          efficiency: 69,
          outputKm: 11.5,
          outputKg: 805,
          materialCount: 58,
          status: "complete",
        },
      ],
      Giáp: [
        {
          machine: "AR-DN-01",
          designSpeed: 7.2,
          actualSpeed: 7.2,
          efficiency: 100,
          outputKm: 1.8,
          outputKg: 425,
          materialCount: 28,
          status: "complete",
        },
        {
          machine: "AR-DN-03",
          designSpeed: 7.0,
          actualSpeed: 6.8,
          efficiency: 97,
          outputKm: 1.6,
          outputKg: 410,
          materialCount: 25,
          status: "complete",
        },
      ],
      Bọc: [
        {
          machine: "SH-DN-02",
          designSpeed: 180,
          actualSpeed: 168,
          efficiency: 93,
          outputKm: 13.5,
          outputKg: 920,
          materialCount: 52,
          status: "complete",
        },
        {
          machine: "SH-DN-05",
          designSpeed: 175,
          actualSpeed: 162,
          efficiency: 93,
          outputKm: 12.8,
          outputKg: 885,
          materialCount: 48,
          status: "complete",
        },
        {
          machine: "SH-DN-07",
          designSpeed: 172,
          actualSpeed: 158,
          efficiency: 92,
          outputKm: 12.2,
          outputKg: 850,
          materialCount: 45,
          status: "missing",
        },
        {
          machine: "SH-DN-09",
          designSpeed: 168,
          actualSpeed: 155,
          efficiency: 92,
          outputKm: 11.8,
          outputKg: 825,
          materialCount: 42,
          status: "complete",
        },
      ],
    },

    // Missing data materials (first 5)
    missingMaterials: [
      { code: "53000789", process: "Xoắn" },
      { code: "56001234", process: "Bọc" },
      { code: "52000890", process: "Kéo" },
      { code: "55000901", process: "Giáp" },
      { code: "53002345", process: "Xoắn" },
    ],
  },
};
